# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Happy blog
tagline: Find the shortest path to Happiness without using linear time algorithms
author: Sahil Yadav
email: yadavsahil5198@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a happy blog. This will dispense happiness as you 
  stare in your screen for continuous 10 minutes. Believe me,
  Trump never lies and I never kid.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://batterylow.me" # the base hostname & protocol for your site
keywords: "Jekyll, blogger, IIT, Mandi"

twitter_username: G3kibatterylow
github_username: me-ydv-5

favicon: "/_includes/favicon.png"
# Build settings
markdown: kramdown
